# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='file_url',
        ),
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='comic',
            name='pages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='dashboard.Series'),
            preserve_default=False,
        ),
    ]
