# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170422_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='series',
            name='author',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
